FROM node:18

WORKDIR /app
# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

RUN npm install

COPY . .

RUN npx react-native run-web

EXPOSE 3000

CMD npx react-native start
